#!/usr/bin/env bash

#this bash script transfers a file from our client to a server

#Checks if all parameters are given
if [ $# -lt 4 ]
   then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   else
	scp -o StrictHostKeyChecking=no -i "$5" "$4" "$3@$2":~
fi
