#!/usr/bin/env bash

#this bash script transfers a file from our client to a server

#Checks if all parameters are given
if [ "$#" -lt 4 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

#Assigns parameters to variables
file_path="$5"
server_ip="$4"
username="$3"
ssh_key_path="$2"

#Transfers the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/ 

#Checks if scp command was successful
if [ $? -eq 0 ];
then
    echo "File transferred successfully."
else
    echo "Error: File transfer failed."
fi
