#!/usr/bin/env bash
#A script that Configures Nginx server to listen on port 80

# removes the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
# configures Nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restarts nginx
service nginx restart
